[package]
name = "carball"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcars = "0.8.10"
log = "0.4.14"
simplelog = "0.10.0"
lazy_static = "1.4.0"
serde = "1.0.126"
serde_json = "1.0.64"
indicatif = "0.16.2"
polars = {version = "0.14.6", features = ["dtype-u8", "parquet"]}
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
chip = "0.0.6"
nalgebra = "0.18.1"
thiserror = "1.0.26"
structopt = "0.3.22"
clap = "2.33.3"

[dependencies.pyo3]
version = "0.14.1"
features = ["auto-initialize"]

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
path = "benches/bench.rs"
name = "bench_parsing"
harness = false

[profile.release] 
debug = true